### ISSUE TITLE
Version 2.0.4 on SpongeForge 1.10.2 not writing to database

### ISSUE THREAD

**Issue by metalus89** [Zerthick/PlayerShopsRPG#36]
I used h2 to check and see if anything was being written to the flat file database and it seems it isn't writing anything at all. I've included a copy of the database with my server after I have set up a shop. I also included my server log file for further review.

[fml-server-latest.zip](https://github.com/Zerthick/PlayerShopsRPG/files/1469693/fml-server-latest.zip)

[data.mv.zip](https://github.com/Zerthick/PlayerShopsRPG/files/1469686/data.mv.zip)

**Comment by Zerthick** [comment]
Everything seems to be working with PlayerShopsRPG-v2.0.4 and spongeforge-1.10.2-2477-5.2.0-BETA-2782.  Would it be possible to get the logs around the time of server shutdown?  With the current implementation of PlayerShopsRPG values will only be written to the db upon server shutdown, I intend to eventually modify this to save values periodically.  What I suspect is happening is that on shutdown some other plugin is throwing an error which prevents PlayerShopsRPG from having its turn to write its data. Based on the log you provided it looks like that keys plugin was written for a different version of Sponge as it is throwing noSuchMethodErrors, it also utilizes the H2 database connection so it may be the source of the issue.

**Comment by metalus89** [comment]
I have since removed the keys plugin and implemented a different market
plugin. I can try to load it up on my new server but the new one is 1.11.2
And not 1.10.2.

**Comment by Zerthick** [comment]
Be sure to use [v2.0.5](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.5) if you do!
